package server

import "errors"

var (
	errProviderAlreadyExists  = errors.New("provider already exists")
	errProviderNotFound       = errors.New("provider not found")
	errProviderNoCustomConfig = errors.New("provider has no custom settings")
	errProviderReadOnly       = errors.New("extension provider catalog is read-only")
	errModelAlreadyExists     = errors.New("model already exists")
	errModelNotFound          = errors.New("model not found")
	errSelectedModelNoImage   = errors.New("selected model does not support image input")
	errAttachmentPathRequired = errors.New("attachment path required")
	errAttachmentPathInvalid  = errors.New("invalid attachment path")
	errAttachmentUnreadable   = errors.New("attachment unreadable")
	errImageTooLarge          = errors.New("image exceeds 20 MiB")
	errUnsupportedContent     = errors.New("unsupported type")
	errTextOrAttachment       = errors.New("text or attachment required")
	errModelUnavailable       = errors.New("unavailable")
	errQueueIDRequiresSteer   = errors.New("queueId requires delivery=steer")
	errQueueIDWithContent     = errors.New("queueId cannot include content")
	errQueueIDWithParent      = errors.New("queueId cannot be used with parentId")

	errWorkspaceOrCWDRequired    = errors.New("workspaceId or cwd required")
	errSessionNotFound           = errors.New("session not found")
	errExtensionRequired         = errors.New("extension required")
	errAppendMessageUserOnly     = errors.New("appendMessage only accepts user messages")
	errNoExtensions              = errors.New("no extensions")
	errAgentTaskStoreUnavailable = errors.New("agent task store is unavailable")
	errMaximumAgentDepth         = errors.New("maximum agent depth")
	errAgentDepthRequiresSession = errors.New("agent depth requires a session")
	errSessionParentCycle        = errors.New("session parent cycle while resolving agent depth")
	errAgentToAndMessageRequired = errors.New("to and message are required")
	errAgentNotFound             = errors.New("agent not found")
	errProviderNoCredential      = errors.New("provider has no configured credential")
	errExtensionFailed           = errors.New("extension failed")
)
