package llmprotocol

import "errors"

var (
	errInvalidAnthropicSSEJSON             = errors.New("invalid Anthropic SSE JSON")
	errAnthropicDeltaNoIndex               = errors.New("anthropic content block delta has no index")
	errAnthropicDeltaNoObject              = errors.New("anthropic content block delta has no delta object")
	errAnthropicDeltaNoType                = errors.New("anthropic content block delta has no type")
	errAnthropicStartNoIndex               = errors.New("anthropic content block start has no index")
	errAnthropicStartNoContentBlock        = errors.New("anthropic content block start has no content_block")
	errAnthropicBlockStartedTwice          = errors.New("anthropic content block started more than once")
	errAnthropicRedactedThinkingNoData     = errors.New("anthropic redacted_thinking has no data")
	errAnthropicToolUseMissingIDOrName     = errors.New("anthropic tool_use is missing id or name")
	errAnthropicToolUseNoInput             = errors.New("anthropic tool_use has no input")
	errAnthropicToolUseInputMustBeObject   = errors.New("anthropic tool_use input must be an object")
	errUnsupportedAnthropicContentBlock    = errors.New("unsupported Anthropic content block type")
	errAnthropicStopNoIndex                = errors.New("anthropic content block stop has no index")
	errAnthropicStopUnknownIndex           = errors.New("anthropic content block stop references unknown index")
	errAnthropicMessageStartNoMessage      = errors.New("anthropic message_start has no message object")
	errAnthropicMessageStartEmptyID        = errors.New("anthropic message_start has empty message id")
	errAnthropicDeltaUnknownIndex          = errors.New("anthropic content block delta references unknown index")
	errAnthropicBlockTypeChanged           = errors.New("anthropic content block changed type")
	errAnthropicToolResultNoToolUseID      = errors.New("anthropic tool_result has no tool_use_id")
	errAnthropicThinkingNoSignature        = errors.New("anthropic thinking block has no signature")
	errAnthropicToolUseNoIDOrName          = errors.New("anthropic tool_use has no id or name")
	errAnthropicToolUseInputNotObject      = errors.New("anthropic tool_use input is not an object")
	errAnthropicToolUseStreamMissingIDName = errors.New("anthropic tool_use stream is missing id or name")

	errInvalidCompletionsSSEJSON           = errors.New("invalid chat completions SSE JSON")
	errCompletionsToolCallNoIndex          = errors.New("chat Completions tool call has no valid index")
	errCompletionsToolCallNoID             = errors.New("chat Completions tool call has no id")
	errCompletionsToolMessageNoCallID      = errors.New("chat Completions tool message has no tool_call_id")
	errCompletionsNoCustomToolCalls        = errors.New("chat Completions does not support custom tool calls")
	errCompletionsAssistantToolCallNoID    = errors.New("chat Completions assistant tool call has no id or name")
	errCompletionsToolCallMissingIDOrName  = errors.New("chat Completions tool call is missing id or name")
	errCompletionsToolCallNoArguments      = errors.New("chat Completions tool call has no arguments")
	errCompletionsToolCallArgsMustBeObject = errors.New("chat Completions tool call arguments must be a JSON object")

	errResponsesInputNotObject             = errors.New("responses input is not an object")
	errResponsesInputEmptyCallID           = errors.New("responses input has empty call_id")
	errInvalidResponsesSSEJSON             = errors.New("invalid Responses SSE JSON")
	errResponsesOutputItemNoItem           = errors.New("responses output item event has no item")
	errResponsesContentPartNoPart          = errors.New("responses content part event has no part")
	errResponsesFunctionCallEmptyCallID    = errors.New("responses function call has empty call_id")
	errResponsesCustomToolCallEmptyCallID  = errors.New("responses custom tool call has empty call_id")
	errResponsesStreamEmptyItemID          = errors.New("responses stream event has empty item_id")
	errResponsesTextNoItemOrIndex          = errors.New("responses text event has no item_id or output_index")
	errResponsesItemEmptyID                = errors.New("responses item has empty id")
	errResponsesItemEmptyCallID            = errors.New("responses item has empty call_id")
	errResponsesReasoningEmptyID           = errors.New("responses reasoning output item has empty id")
	errResponsesFunctionCallMissing        = errors.New("responses function call is missing")
	errResponsesFunctionCallArgsMustObject = errors.New("responses function call arguments must be a JSON object")

	errProviderSSEEndedEarly  = errors.New("provider SSE stream ended before a terminal response event")
	errProviderResponseFailed = errors.New("provider response failed")
)
